mysql:
  url: jdbc:mysql://mysql:3306/Network_Traffic_Analysis_System?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  username: root
  password: 123456

redis:
  host: redis
  port: 6379

kafka:
  bootstrapServers: kafka:9092
  groupId: flink-group
