# 数据库相关配置
spring:
  application:
    name: hdu-traffic-analysis
  datasource:
    mysql:
      url: jdbc:mysql://192.168.112.109:3306/Network_Traffic_Analysis_System
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

    sqlserver:
      url: jdbc:sqlserver://192.168.100.202:1433;databaseName=easytong_plus;encrypt=false
      username: sa
      password: Hzsun310012
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  # 时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# 日志级别配置
logging:
  level:
    com:
      hdu:
        controller: info
        mapper: debug
        service: info
# mybatis相关配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.hdu.entity

# 分页插件相关配置
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

pa:
  api:
    base-url: 192.168.102.100
    access-token:

aaa:
  api:
    base-url: http://aaa-device-ip
    access-token:


    redis:
      host: 192.168.112.109
      #auth: 123456
      database: 0
      port: 6379

  spring:
    kafka:
      consumer:
        bootstrap-servers: 192.168.112.109:9092
        group-id: risk-result-group
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: com.hdu.result
